version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    command: npm run start
    # network_mode: host   <===< Enable this to connect to a db in localhost.
