version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file: .env
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: npm run dev

  db:
    image: postgres:11.4-alpine
    restart: unless-stopped
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test

networks:
  app-network:
    driver: bridge

volumes:
  db:
  app: